package com.seeyon.orgcenter.manage.function.entity;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table org_function
 *
 * @mbg.generated do_not_delete_during_merge Wed Oct 14 00:13:41 CST 2020
 */
public class OrgFunction {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_function.ID
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_function.APP_ID
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    private Long appId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_function.NAME
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_function.CODE
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_function.URL
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_function.TYPE
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_function.PARENT_FUN_ID
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    private Long parentFunId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_function.CREATE_TIME
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_function.UPDATE_TIME
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_function.ICON
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    private String icon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_function.PATH
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    private String path;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_function.IS_SHOW
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    private Integer isShow;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_function.IS_CHECK
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    private Integer isCheck;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_function.IS_CONTROL
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    private Integer isControl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_function.SHORTCUT
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    private Integer shortcut;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_function.SHORTCUT_ICON
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    private String shortcutIcon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_function.LEVEL
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    private Integer level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_function.IS_DELETED
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    private Integer isDeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_function.ID
     *
     * @return the value of org_function.ID
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_function.ID
     *
     * @param id the value for org_function.ID
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_function.APP_ID
     *
     * @return the value of org_function.APP_ID
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    public Long getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_function.APP_ID
     *
     * @param appId the value for org_function.APP_ID
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    public void setAppId(Long appId) {
        this.appId = appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_function.NAME
     *
     * @return the value of org_function.NAME
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_function.NAME
     *
     * @param name the value for org_function.NAME
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_function.CODE
     *
     * @return the value of org_function.CODE
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_function.CODE
     *
     * @param code the value for org_function.CODE
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_function.URL
     *
     * @return the value of org_function.URL
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_function.URL
     *
     * @param url the value for org_function.URL
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_function.TYPE
     *
     * @return the value of org_function.TYPE
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_function.TYPE
     *
     * @param type the value for org_function.TYPE
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_function.PARENT_FUN_ID
     *
     * @return the value of org_function.PARENT_FUN_ID
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    public Long getParentFunId() {
        return parentFunId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_function.PARENT_FUN_ID
     *
     * @param parentFunId the value for org_function.PARENT_FUN_ID
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    public void setParentFunId(Long parentFunId) {
        this.parentFunId = parentFunId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_function.CREATE_TIME
     *
     * @return the value of org_function.CREATE_TIME
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_function.CREATE_TIME
     *
     * @param createTime the value for org_function.CREATE_TIME
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_function.UPDATE_TIME
     *
     * @return the value of org_function.UPDATE_TIME
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_function.UPDATE_TIME
     *
     * @param updateTime the value for org_function.UPDATE_TIME
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_function.ICON
     *
     * @return the value of org_function.ICON
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_function.ICON
     *
     * @param icon the value for org_function.ICON
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    public void setIcon(String icon) {
        this.icon = icon == null ? null : icon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_function.PATH
     *
     * @return the value of org_function.PATH
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_function.PATH
     *
     * @param path the value for org_function.PATH
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_function.IS_SHOW
     *
     * @return the value of org_function.IS_SHOW
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    public Integer getIsShow() {
        return isShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_function.IS_SHOW
     *
     * @param isShow the value for org_function.IS_SHOW
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    public void setIsShow(Integer isShow) {
        this.isShow = isShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_function.IS_CHECK
     *
     * @return the value of org_function.IS_CHECK
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    public Integer getIsCheck() {
        return isCheck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_function.IS_CHECK
     *
     * @param isCheck the value for org_function.IS_CHECK
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    public void setIsCheck(Integer isCheck) {
        this.isCheck = isCheck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_function.IS_CONTROL
     *
     * @return the value of org_function.IS_CONTROL
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    public Integer getIsControl() {
        return isControl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_function.IS_CONTROL
     *
     * @param isControl the value for org_function.IS_CONTROL
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    public void setIsControl(Integer isControl) {
        this.isControl = isControl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_function.SHORTCUT
     *
     * @return the value of org_function.SHORTCUT
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    public Integer getShortcut() {
        return shortcut;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_function.SHORTCUT
     *
     * @param shortcut the value for org_function.SHORTCUT
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    public void setShortcut(Integer shortcut) {
        this.shortcut = shortcut;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_function.SHORTCUT_ICON
     *
     * @return the value of org_function.SHORTCUT_ICON
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    public String getShortcutIcon() {
        return shortcutIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_function.SHORTCUT_ICON
     *
     * @param shortcutIcon the value for org_function.SHORTCUT_ICON
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    public void setShortcutIcon(String shortcutIcon) {
        this.shortcutIcon = shortcutIcon == null ? null : shortcutIcon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_function.LEVEL
     *
     * @return the value of org_function.LEVEL
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_function.LEVEL
     *
     * @param level the value for org_function.LEVEL
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_function.IS_DELETED
     *
     * @return the value of org_function.IS_DELETED
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    public Integer getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_function.IS_DELETED
     *
     * @param isDeleted the value for org_function.IS_DELETED
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    public void setIsDeleted(Integer isDeleted) {
        this.isDeleted = isDeleted;
    }
}
