package com.seeyon.orgcenter.manage.function.mapper;

import com.seeyon.orgcenter.common.basemapper.BaseMapper;
import com.seeyon.orgcenter.manage.function.entity.OrgFunction;
import io.swagger.annotations.ApiModel;
import org.apache.ibatis.annotations.Mapper;


@ApiModel("fun")
@Mapper
public interface OrgFunctionMapper extends BaseMapper<OrgFunction> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_function
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_function
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    int insert(OrgFunction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_function
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    int insertSelective(OrgFunction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_function
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    OrgFunction selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_function
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    int updateByPrimaryKeySelective(OrgFunction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_function
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    int updateByPrimaryKey(OrgFunction record);
}
