package com.seeyon.orgcenter.manage.tree.mapper;

import com.seeyon.orgcenter.manage.tree.entity.OrgTree;
import org.apache.ibatis.annotations.Mapper;


@Mapper
public interface OrgTreeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_tree
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_tree
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    int insert(OrgTree record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_tree
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    int insertSelective(OrgTree record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_tree
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    OrgTree selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_tree
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    int updateByPrimaryKeySelective(OrgTree record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_tree
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    int updateByPrimaryKey(OrgTree record);
}
