package com.seeyon.orgcenter.manage.role.mapper;

import com.seeyon.orgcenter.common.basemapper.BaseMapper;
import com.seeyon.orgcenter.manage.role.entity.OrgPermissionFunRelation;
import io.swagger.annotations.ApiModel;
import org.apache.ibatis.annotations.Mapper;


@ApiModel("角色fun权限")
@Mapper
public interface OrgPermissionFunRelationMapper extends BaseMapper<OrgPermissionFunRelation> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_permission_fun_relation
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_permission_fun_relation
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    int insert(OrgPermissionFunRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_permission_fun_relation
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    int insertSelective(OrgPermissionFunRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_permission_fun_relation
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    OrgPermissionFunRelation selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_permission_fun_relation
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    int updateByPrimaryKeySelective(OrgPermissionFunRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_permission_fun_relation
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    int updateByPrimaryKey(OrgPermissionFunRelation record);
}
