package com.seeyon.orgcenter.manage.role.mapper;

import com.seeyon.orgcenter.common.basemapper.BaseMapper;
import com.seeyon.orgcenter.manage.role.entity.OrgRole;
import io.swagger.annotations.Api;
import io.swagger.annotations.ApiModel;
import org.apache.ibatis.annotations.Mapper;


@ApiModel("角色")
@Mapper
public interface OrgRoleMapper extends BaseMapper<OrgRole> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_role
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_role
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    int insert(OrgRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_role
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    int insertSelective(OrgRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_role
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    OrgRole selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_role
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    int updateByPrimaryKeySelective(OrgRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_role
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    int updateByPrimaryKey(OrgRole record);
}
