package com.seeyon.orgcenter.manage.role.mapper;

import com.seeyon.orgcenter.manage.role.entity.OrgRole;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface OrgRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_role
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_role
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    int insert(OrgRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_role
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    int insertSelective(OrgRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_role
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    OrgRole selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_role
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    int updateByPrimaryKeySelective(OrgRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_role
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    int updateByPrimaryKey(OrgRole record);
}
