package com.seeyon.orgcenter.manage.account.mapper;

import com.seeyon.orgcenter.manage.account.entity.OrgAppAccountRoleRelation;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface OrgAppAccountRoleRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_app_account_role_relation
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_app_account_role_relation
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    int insert(OrgAppAccountRoleRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_app_account_role_relation
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    int insertSelective(OrgAppAccountRoleRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_app_account_role_relation
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    OrgAppAccountRoleRelation selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_app_account_role_relation
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    int updateByPrimaryKeySelective(OrgAppAccountRoleRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_app_account_role_relation
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    int updateByPrimaryKey(OrgAppAccountRoleRelation record);
}
