package com.seeyon.orgcenter.manage.account.mapper;

import com.seeyon.orgcenter.common.basemapper.BaseMapper;
import com.seeyon.orgcenter.manage.account.entity.OrgAccount;
import io.swagger.annotations.ApiModel;
import org.apache.ibatis.annotations.Mapper;

@ApiModel("账号")
@Mapper
public interface OrgAccountMapper  extends BaseMapper<OrgAccount> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_account
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_account
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    int insert(OrgAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_account
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    int insertSelective(OrgAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_account
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    OrgAccount selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_account
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    int updateByPrimaryKeySelective(OrgAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_account
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    int updateByPrimaryKey(OrgAccount record);
}
