package com.seeyon.orgcenter.manage.account.entity;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table org_account
 *
 * @mbg.generated do_not_delete_during_merge Wed Oct 14 00:13:41 CST 2020
 */
public class OrgAccount {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_account.ID
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_account.LOGIN_NAME
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    private String loginName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_account.CREDENTIAL_VALUE
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    private String credentialValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_account.CLASS_NAME
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    private String className;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_account.EXPIRATION_DATE
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    private Date expirationDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_account.IS_ENABLE
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    private Integer isEnable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_account.CREATE_TIME
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_account.UPDATE_TIME
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_account.IS_DELETED
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    private Integer isDeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_account.ID
     *
     * @return the value of org_account.ID
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_account.ID
     *
     * @param id the value for org_account.ID
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_account.LOGIN_NAME
     *
     * @return the value of org_account.LOGIN_NAME
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_account.LOGIN_NAME
     *
     * @param loginName the value for org_account.LOGIN_NAME
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName == null ? null : loginName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_account.CREDENTIAL_VALUE
     *
     * @return the value of org_account.CREDENTIAL_VALUE
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    public String getCredentialValue() {
        return credentialValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_account.CREDENTIAL_VALUE
     *
     * @param credentialValue the value for org_account.CREDENTIAL_VALUE
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    public void setCredentialValue(String credentialValue) {
        this.credentialValue = credentialValue == null ? null : credentialValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_account.CLASS_NAME
     *
     * @return the value of org_account.CLASS_NAME
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    public String getClassName() {
        return className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_account.CLASS_NAME
     *
     * @param className the value for org_account.CLASS_NAME
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    public void setClassName(String className) {
        this.className = className == null ? null : className.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_account.EXPIRATION_DATE
     *
     * @return the value of org_account.EXPIRATION_DATE
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    public Date getExpirationDate() {
        return expirationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_account.EXPIRATION_DATE
     *
     * @param expirationDate the value for org_account.EXPIRATION_DATE
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    public void setExpirationDate(Date expirationDate) {
        this.expirationDate = expirationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_account.IS_ENABLE
     *
     * @return the value of org_account.IS_ENABLE
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    public Integer getIsEnable() {
        return isEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_account.IS_ENABLE
     *
     * @param isEnable the value for org_account.IS_ENABLE
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    public void setIsEnable(Integer isEnable) {
        this.isEnable = isEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_account.CREATE_TIME
     *
     * @return the value of org_account.CREATE_TIME
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_account.CREATE_TIME
     *
     * @param createTime the value for org_account.CREATE_TIME
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_account.UPDATE_TIME
     *
     * @return the value of org_account.UPDATE_TIME
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_account.UPDATE_TIME
     *
     * @param updateTime the value for org_account.UPDATE_TIME
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_account.IS_DELETED
     *
     * @return the value of org_account.IS_DELETED
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    public Integer getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_account.IS_DELETED
     *
     * @param isDeleted the value for org_account.IS_DELETED
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    public void setIsDeleted(Integer isDeleted) {
        this.isDeleted = isDeleted;
    }
}
