package com.seeyon.orgcenter.manage.role.entity;

import io.swagger.annotations.ApiModel;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table org_permission_fun_relation
 *
 * @mbg.generated do_not_delete_during_merge Wed Oct 14 00:13:41 CST 2020
 */
@ApiModel("角色fun权限")
public class OrgPermissionFunRelation {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_permission_fun_relation.ID
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_permission_fun_relation.APP_ID
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    private Long appId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_permission_fun_relation.NAME
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_permission_fun_relation.FUN_ID
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    private Long funId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_permission_fun_relation.ROLE_ID
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    private Long roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_permission_fun_relation.ID
     *
     * @return the value of org_permission_fun_relation.ID
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_permission_fun_relation.ID
     *
     * @param id the value for org_permission_fun_relation.ID
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_permission_fun_relation.APP_ID
     *
     * @return the value of org_permission_fun_relation.APP_ID
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    public Long getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_permission_fun_relation.APP_ID
     *
     * @param appId the value for org_permission_fun_relation.APP_ID
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    public void setAppId(Long appId) {
        this.appId = appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_permission_fun_relation.NAME
     *
     * @return the value of org_permission_fun_relation.NAME
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_permission_fun_relation.NAME
     *
     * @param name the value for org_permission_fun_relation.NAME
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_permission_fun_relation.FUN_ID
     *
     * @return the value of org_permission_fun_relation.FUN_ID
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    public Long getFunId() {
        return funId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_permission_fun_relation.FUN_ID
     *
     * @param funId the value for org_permission_fun_relation.FUN_ID
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    public void setFunId(Long funId) {
        this.funId = funId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_permission_fun_relation.ROLE_ID
     *
     * @return the value of org_permission_fun_relation.ROLE_ID
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_permission_fun_relation.ROLE_ID
     *
     * @param roleId the value for org_permission_fun_relation.ROLE_ID
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }
}
