package com.seeyon.orgcenter.manage.role.entity;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table org_role
 *
 * @mbg.generated do_not_delete_during_merge Wed Oct 14 00:13:41 CST 2020
 */
public class OrgRole {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_role.ID
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_role.NAME
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_role.CODE
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_role.APP_ID
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    private Long appId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_role.IS_DELETED
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    private Integer isDeleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_role.IS_ENABLE
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    private Integer isEnable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_role.CREATE_TIME
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_role.UPDATE_TIME
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_role.IS_GLOBAL
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    private Integer isGlobal;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_role.ID
     *
     * @return the value of org_role.ID
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_role.ID
     *
     * @param id the value for org_role.ID
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_role.NAME
     *
     * @return the value of org_role.NAME
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_role.NAME
     *
     * @param name the value for org_role.NAME
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_role.CODE
     *
     * @return the value of org_role.CODE
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_role.CODE
     *
     * @param code the value for org_role.CODE
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_role.APP_ID
     *
     * @return the value of org_role.APP_ID
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    public Long getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_role.APP_ID
     *
     * @param appId the value for org_role.APP_ID
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    public void setAppId(Long appId) {
        this.appId = appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_role.IS_DELETED
     *
     * @return the value of org_role.IS_DELETED
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    public Integer getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_role.IS_DELETED
     *
     * @param isDeleted the value for org_role.IS_DELETED
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    public void setIsDeleted(Integer isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_role.IS_ENABLE
     *
     * @return the value of org_role.IS_ENABLE
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    public Integer getIsEnable() {
        return isEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_role.IS_ENABLE
     *
     * @param isEnable the value for org_role.IS_ENABLE
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    public void setIsEnable(Integer isEnable) {
        this.isEnable = isEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_role.CREATE_TIME
     *
     * @return the value of org_role.CREATE_TIME
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_role.CREATE_TIME
     *
     * @param createTime the value for org_role.CREATE_TIME
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_role.UPDATE_TIME
     *
     * @return the value of org_role.UPDATE_TIME
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_role.UPDATE_TIME
     *
     * @param updateTime the value for org_role.UPDATE_TIME
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_role.IS_GLOBAL
     *
     * @return the value of org_role.IS_GLOBAL
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    public Integer getIsGlobal() {
        return isGlobal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_role.IS_GLOBAL
     *
     * @param isGlobal the value for org_role.IS_GLOBAL
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    public void setIsGlobal(Integer isGlobal) {
        this.isGlobal = isGlobal;
    }
}
