package com.seeyon.orgcenter.manage.tree.entity;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table org_tree
 *
 * @mbg.generated do_not_delete_during_merge Wed Oct 14 00:13:41 CST 2020
 */
public class OrgTree {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_tree.ID
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_tree.NAME
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_tree.CODE
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_tree.IS_GLOBAL
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    private Integer isGlobal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_tree.IS_ENABLE
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    private Integer isEnable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_tree.IS_DELETED
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    private Integer isDeleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_tree.PARENT_ORGAN_ID
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    private Long parentOrganId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_tree.ORGAN_ID
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    private Long organId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_tree.LEVEL
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    private Integer level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_tree.PATH
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    private String path;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_tree.CREATE_TIME
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_tree.UPDATE_TIME
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_tree.CREATE_USER
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    private Long createUser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_tree.ID
     *
     * @return the value of org_tree.ID
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_tree.ID
     *
     * @param id the value for org_tree.ID
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_tree.NAME
     *
     * @return the value of org_tree.NAME
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_tree.NAME
     *
     * @param name the value for org_tree.NAME
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_tree.CODE
     *
     * @return the value of org_tree.CODE
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_tree.CODE
     *
     * @param code the value for org_tree.CODE
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_tree.IS_GLOBAL
     *
     * @return the value of org_tree.IS_GLOBAL
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    public Integer getIsGlobal() {
        return isGlobal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_tree.IS_GLOBAL
     *
     * @param isGlobal the value for org_tree.IS_GLOBAL
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    public void setIsGlobal(Integer isGlobal) {
        this.isGlobal = isGlobal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_tree.IS_ENABLE
     *
     * @return the value of org_tree.IS_ENABLE
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    public Integer getIsEnable() {
        return isEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_tree.IS_ENABLE
     *
     * @param isEnable the value for org_tree.IS_ENABLE
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    public void setIsEnable(Integer isEnable) {
        this.isEnable = isEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_tree.IS_DELETED
     *
     * @return the value of org_tree.IS_DELETED
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    public Integer getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_tree.IS_DELETED
     *
     * @param isDeleted the value for org_tree.IS_DELETED
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    public void setIsDeleted(Integer isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_tree.PARENT_ORGAN_ID
     *
     * @return the value of org_tree.PARENT_ORGAN_ID
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    public Long getParentOrganId() {
        return parentOrganId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_tree.PARENT_ORGAN_ID
     *
     * @param parentOrganId the value for org_tree.PARENT_ORGAN_ID
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    public void setParentOrganId(Long parentOrganId) {
        this.parentOrganId = parentOrganId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_tree.ORGAN_ID
     *
     * @return the value of org_tree.ORGAN_ID
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    public Long getOrganId() {
        return organId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_tree.ORGAN_ID
     *
     * @param organId the value for org_tree.ORGAN_ID
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    public void setOrganId(Long organId) {
        this.organId = organId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_tree.LEVEL
     *
     * @return the value of org_tree.LEVEL
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_tree.LEVEL
     *
     * @param level the value for org_tree.LEVEL
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_tree.PATH
     *
     * @return the value of org_tree.PATH
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_tree.PATH
     *
     * @param path the value for org_tree.PATH
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_tree.CREATE_TIME
     *
     * @return the value of org_tree.CREATE_TIME
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_tree.CREATE_TIME
     *
     * @param createTime the value for org_tree.CREATE_TIME
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_tree.UPDATE_TIME
     *
     * @return the value of org_tree.UPDATE_TIME
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_tree.UPDATE_TIME
     *
     * @param updateTime the value for org_tree.UPDATE_TIME
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_tree.CREATE_USER
     *
     * @return the value of org_tree.CREATE_USER
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    public Long getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_tree.CREATE_USER
     *
     * @param createUser the value for org_tree.CREATE_USER
     *
     * @mbg.generated Wed Oct 14 00:13:41 CST 2020
     */
    public void setCreateUser(Long createUser) {
        this.createUser = createUser;
    }
}
